//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
// test/vectors/merkle_inclusion.ts
//
// RFC 9162 §2.1.3 inclusion proof verification corpus, transcribed
// verbatim from transparency-dev/merkle's testdata/inclusion directory.
// Each record drives one verifier probe; `wantErr` flags the
// records that must reject (malformed proof, wrong root, out-of-range
// leaf index, etc.).
//
// Source:
//   transparency-dev/merkle, directory testdata/inclusion
//   @see https://github.com/transparency-dev/merkle/tree/fefdc92cb8cbf22503f34fe1d106d150a9204370/testdata/inclusion
//   pin: fefdc92cb8cbf22503f34fe1d106d150a9204370
//
// Fields use Go's encoding/json default of base64 std-padded for byte
// slices. The runner base64-decodes on use; raw strings are preserved
// here to keep byte-for-byte parity with the upstream JSON.

export interface MerkleInclusionRecord {
	readonly source:      string;
	readonly desc:        string;
	readonly leafIdx:     number;
	readonly treeSize:    number;
	readonly rootB64:     string;
	readonly leafHashB64: string;
	readonly proofB64:    readonly string[] | null;
	readonly wantErr:     boolean;
}

export const merkleInclusionRecords: readonly MerkleInclusionRecord[] = [
	{
		source: 'inclusion/0/empty-root.json',
		desc: 'empty root',
		leafIdx: 0,
		treeSize: 1,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: null,
		wantErr: true,
	},
	{
		source: 'inclusion/0/happy-path.json',
		desc: 'happy path',
		leafIdx: 0,
		treeSize: 1,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: null,
		wantErr: false,
	},
	{
		source: 'inclusion/0/leafIdx-XOR-@2.json',
		desc: 'leafIdx XOR @2',
		leafIdx: 2,
		treeSize: 1,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: null,
		wantErr: true,
	},
	{
		source: 'inclusion/0/leafIdx-plus-@1.json',
		desc: 'leafIdx plus @1',
		leafIdx: 1,
		treeSize: 1,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: null,
		wantErr: true,
	},
	{
		source: 'inclusion/0/leafIdx-sub-@1.json',
		desc: 'leafIdx sub @1',
		leafIdx: 18446744073709552000,
		treeSize: 1,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: null,
		wantErr: true,
	},
	{
		source: 'inclusion/0/preceding-garbage.json',
		desc: 'preceding garbage',
		leafIdx: 0,
		treeSize: 1,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/0/preceding-root.json',
		desc: 'preceding root',
		leafIdx: 0,
		treeSize: 1,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/0/random-root.json',
		desc: 'random root',
		leafIdx: 0,
		treeSize: 1,
		rootB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: null,
		wantErr: true,
	},
	{
		source: 'inclusion/0/trailing-garbage.json',
		desc: 'trailing garbage',
		leafIdx: 0,
		treeSize: 1,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/0/trailing-root.json',
		desc: 'trailing root',
		leafIdx: 0,
		treeSize: 1,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/0/treeSize-div-@2.json',
		desc: 'treeSize div @2',
		leafIdx: 0,
		treeSize: 0,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: null,
		wantErr: true,
	},
	{
		source: 'inclusion/0/treeSize-mul-@2.json',
		desc: 'treeSize mul @2',
		leafIdx: 0,
		treeSize: 2,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: null,
		wantErr: true,
	},
	{
		source: 'inclusion/0/wrong-leaf.json',
		desc: 'wrong leaf',
		leafIdx: 0,
		treeSize: 1,
		rootB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		leafHashB64: 'V3JvbmdMZWFm',
		proofB64: null,
		wantErr: true,
	},
	{
		source: 'inclusion/1/empty-root.json',
		desc: 'empty root',
		leafIdx: 0,
		treeSize: 8,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/happy-path.json',
		desc: 'happy path',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: false,
	},
	{
		source: 'inclusion/1/inserted-component.json',
		desc: 'inserted component',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/leafIdx-XOR-@2.json',
		desc: 'leafIdx XOR @2',
		leafIdx: 2,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/leafIdx-plus-@1.json',
		desc: 'leafIdx plus @1',
		leafIdx: 1,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/leafIdx-sub-@1.json',
		desc: 'leafIdx sub @1',
		leafIdx: 18446744073709552000,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/modified-proof[0]-bit-@3.json',
		desc: 'modified proof[0] bit @3',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'nqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/modified-proof[1]-bit-@3.json',
		desc: 'modified proof[1] bit @3',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Vwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/modified-proof[2]-bit-@3.json',
		desc: 'modified proof[2] bit @3',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'Y0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/preceding-garbage.json',
		desc: 'preceding garbage',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'',
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/preceding-root.json',
		desc: 'preceding root',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/random-root.json',
		desc: 'random root',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/removed-component.json',
		desc: 'removed component',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/trailing-garbage.json',
		desc: 'trailing garbage',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
			'',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/trailing-root.json',
		desc: 'trailing root',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
			'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/treeSize-div-@2.json',
		desc: 'treeSize div @2',
		leafIdx: 0,
		treeSize: 4,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/treeSize-mul-@2.json',
		desc: 'treeSize mul @2',
		leafIdx: 0,
		treeSize: 16,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/1/wrong-leaf.json',
		desc: 'wrong leaf',
		leafIdx: 0,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'V3JvbmdMZWFm',
		proofB64: [
			'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'a0eq8p7jwq+a+Im8H7klTavTEXfxYjLdaqsDXKOb9uQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/empty-root.json',
		desc: 'empty root',
		leafIdx: 5,
		treeSize: 8,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/happy-path.json',
		desc: 'happy path',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: false,
	},
	{
		source: 'inclusion/2/inserted-component.json',
		desc: 'inserted component',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/leafIdx-XOR-@2.json',
		desc: 'leafIdx XOR @2',
		leafIdx: 7,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/leafIdx-plus-@1.json',
		desc: 'leafIdx plus @1',
		leafIdx: 6,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/leafIdx-sub-@1.json',
		desc: 'leafIdx sub @1',
		leafIdx: 4,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/modified-proof[0]-bit-@3.json',
		desc: 'modified proof[0] bit @3',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'tBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/modified-proof[1]-bit-@3.json',
		desc: 'modified proof[1] bit @3',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'woVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/modified-proof[2]-bit-@3.json',
		desc: 'modified proof[2] bit @3',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'237kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/preceding-garbage.json',
		desc: 'preceding garbage',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/preceding-root.json',
		desc: 'preceding root',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/random-root.json',
		desc: 'random root',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/removed-component.json',
		desc: 'removed component',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/trailing-garbage.json',
		desc: 'trailing garbage',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
			'',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/trailing-root.json',
		desc: 'trailing root',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
			'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/treeSize-div-@2.json',
		desc: 'treeSize div @2',
		leafIdx: 5,
		treeSize: 4,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/treeSize-mul-@2.json',
		desc: 'treeSize mul @2',
		leafIdx: 5,
		treeSize: 16,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'QnGia+DYqE8L1UyMMC58s6O10fpngKQLzOKHNHfatlg=',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/2/wrong-leaf.json',
		desc: 'wrong leaf',
		leafIdx: 5,
		treeSize: 8,
		rootB64: 'XcnaeacGWamtVZy3Ad7ZoqudgjqtL0lgz+Nw7/RgQyg=',
		leafHashB64: 'V3JvbmdMZWFm',
		proofB64: [
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'yoVOoSjtBQtBs1/8G4e46yveRh6eO1WW7Oa51ZdaCuA=',
			'037kGJdt2VdTwcc4Yrk5j6Kiz5tP8P3+izDNlSCWFLc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/empty-root.json',
		desc: 'empty root',
		leafIdx: 2,
		treeSize: 3,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/happy-path.json',
		desc: 'happy path',
		leafIdx: 2,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: false,
	},
	{
		source: 'inclusion/3/leafIdx-XOR-@2.json',
		desc: 'leafIdx XOR @2',
		leafIdx: 0,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/leafIdx-plus-@1.json',
		desc: 'leafIdx plus @1',
		leafIdx: 3,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/leafIdx-sub-@1.json',
		desc: 'leafIdx sub @1',
		leafIdx: 1,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/modified-proof[0]-bit-@3.json',
		desc: 'modified proof[0] bit @3',
		leafIdx: 2,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'8sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/preceding-garbage.json',
		desc: 'preceding garbage',
		leafIdx: 2,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'',
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/preceding-root.json',
		desc: 'preceding root',
		leafIdx: 2,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/random-root.json',
		desc: 'random root',
		leafIdx: 2,
		treeSize: 3,
		rootB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/removed-component.json',
		desc: 'removed component',
		leafIdx: 2,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/3/trailing-garbage.json',
		desc: 'trailing garbage',
		leafIdx: 2,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
			'',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/trailing-root.json',
		desc: 'trailing root',
		leafIdx: 2,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
			'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/treeSize-div-@2.json',
		desc: 'treeSize div @2',
		leafIdx: 2,
		treeSize: 1,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/treeSize-mul-@2.json',
		desc: 'treeSize mul @2',
		leafIdx: 2,
		treeSize: 6,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'ApjRIpBtz8EIkstTpzmS/FufST6kybrbJ7eRtBJ6f+c=',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/3/wrong-leaf.json',
		desc: 'wrong leaf',
		leafIdx: 2,
		treeSize: 3,
		rootB64: 'rra8/idLcKFPsGel5VeCZNsPqbUa9eC6FZFY8yngbnc=',
		leafHashB64: 'V3JvbmdMZWFm',
		proofB64: [
			'+sVCA+fMaWzw38tCySodnbr3CtnmIfS9jZhmLwDjwSU=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/empty-root.json',
		desc: 'empty root',
		leafIdx: 1,
		treeSize: 5,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/happy-path.json',
		desc: 'happy path',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: false,
	},
	{
		source: 'inclusion/4/inserted-component.json',
		desc: 'inserted component',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/leafIdx-XOR-@2.json',
		desc: 'leafIdx XOR @2',
		leafIdx: 3,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/leafIdx-plus-@1.json',
		desc: 'leafIdx plus @1',
		leafIdx: 2,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/leafIdx-sub-@1.json',
		desc: 'leafIdx sub @1',
		leafIdx: 0,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/modified-proof[0]-bit-@3.json',
		desc: 'modified proof[0] bit @3',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'ZjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/modified-proof[1]-bit-@3.json',
		desc: 'modified proof[1] bit @3',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Vwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/modified-proof[2]-bit-@3.json',
		desc: 'modified proof[2] bit @3',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'tBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/preceding-garbage.json',
		desc: 'preceding garbage',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'',
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/preceding-root.json',
		desc: 'preceding root',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/random-root.json',
		desc: 'random root',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/removed-component.json',
		desc: 'removed component',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/trailing-garbage.json',
		desc: 'trailing garbage',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/trailing-root.json',
		desc: 'trailing root',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
			'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/treeSize-div-@2.json',
		desc: 'treeSize div @2',
		leafIdx: 1,
		treeSize: 2,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/treeSize-mul-@2.json',
		desc: 'treeSize mul @2',
		leafIdx: 1,
		treeSize: 10,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/4/wrong-leaf.json',
		desc: 'wrong leaf',
		leafIdx: 1,
		treeSize: 5,
		rootB64: 'Tju7H3tHjc/nH7YxYxUZo7yhLJrvyhYSv85ME6hiZNQ=',
		leafHashB64: 'V3JvbmdMZWFm',
		proofB64: [
			'bjQLnP+zepicpUTmu3gKLHiQHT+zNzh2hRGjBhevoB0=',
			'Xwg/ChozygdqlSeYMlgNs+DvRYS9/x9UyKNg9Q3jAx4=',
			'vBoGQ7EuTS18d5GPROD095qDi2z57FtcKD4fTYhZnms=',
		],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/0/empty-root-and-random-leaf.json',
		desc: 'empty root and random leaf',
		leafIdx: 0,
		treeSize: 0,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/0/empty-root.json',
		desc: 'empty root',
		leafIdx: 0,
		treeSize: 0,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: '',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/0/random-leaf.json',
		desc: 'random leaf',
		leafIdx: 0,
		treeSize: 0,
		rootB64: '',
		leafHashB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/1/empty-root-and-random-leaf.json',
		desc: 'empty root and random leaf',
		leafIdx: 0,
		treeSize: 1,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/1/empty-root.json',
		desc: 'empty root',
		leafIdx: 0,
		treeSize: 1,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: '',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/1/random-leaf.json',
		desc: 'random leaf',
		leafIdx: 0,
		treeSize: 1,
		rootB64: '',
		leafHashB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/2/empty-root-and-random-leaf.json',
		desc: 'empty root and random leaf',
		leafIdx: 1,
		treeSize: 0,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/2/empty-root.json',
		desc: 'empty root',
		leafIdx: 1,
		treeSize: 0,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: '',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/2/random-leaf.json',
		desc: 'random leaf',
		leafIdx: 1,
		treeSize: 0,
		rootB64: '',
		leafHashB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/3/empty-root-and-random-leaf.json',
		desc: 'empty root and random leaf',
		leafIdx: 2,
		treeSize: 1,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/3/empty-root.json',
		desc: 'empty root',
		leafIdx: 2,
		treeSize: 1,
		rootB64: '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=',
		leafHashB64: '',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/additional/3/random-leaf.json',
		desc: 'random leaf',
		leafIdx: 2,
		treeSize: 1,
		rootB64: '',
		leafHashB64: 'q6yroAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAGHgASNFY=',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/single-entry/empty-leaf.json',
		desc: 'empty leaf',
		leafIdx: 0,
		treeSize: 1,
		rootB64: 'DTrtAjFI/9KiWfvQzcf7PPl1ZYdg03dbgq9vkKrMLfw=',
		leafHashB64: '',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/single-entry/empty-root-and-leaf.json',
		desc: 'empty root and leaf',
		leafIdx: 0,
		treeSize: 1,
		rootB64: '',
		leafHashB64: '',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/single-entry/empty-root.json',
		desc: 'empty root',
		leafIdx: 0,
		treeSize: 1,
		rootB64: '',
		leafHashB64: 'DTrtAjFI/9KiWfvQzcf7PPl1ZYdg03dbgq9vkKrMLfw=',
		proofB64: [],
		wantErr: true,
	},
	{
		source: 'inclusion/single-entry/matching-root-and-leaf.json',
		desc: 'matching root and leaf',
		leafIdx: 0,
		treeSize: 1,
		rootB64: 'DTrtAjFI/9KiWfvQzcf7PPl1ZYdg03dbgq9vkKrMLfw=',
		leafHashB64: 'DTrtAjFI/9KiWfvQzcf7PPl1ZYdg03dbgq9vkKrMLfw=',
		proofB64: [],
		wantErr: false,
	},
];
