//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
// test/vitest/ctr_vectors.ts
//
// Authoritative CTR mode test vectors, ported from:
// sources/leviathan/test/spec/09_ctr_vectors.test.ts
//
// Generated by ctr_harness.c (floppy1 reference implementation) on darwin-arm64.
// These are the ground truth for WASM CTR mode correctness.

export interface CtrVector {
  label:  string
  key:    string  // hex
  nonce:  string  // hex (16 bytes = 32 hex chars)
  pt:     string  // hex
  ct:     string  // hex
  blocks: number
}

export const CTR_VECTORS: CtrVector[] = [
	{
		label: 'A',
		key: '00000000000000000000000000000000',                            // 128-bit all-zero key
		nonce: '00000000000000000000000000000000',
		pt: '000000000000000000000000000000000000000000000000' +           // 3 blocks all-zero PT
            '000000000000000000000000000000000000000000000000',
		ct: 'E9BA668276B81896D093A9E67AB12036' +                          // block 0
            'BC0ABF8C2037A9263586DE6BA1CEED9B' +                          // block 1
            '0F250F3B1F294E54A3E34512B0AB5D0C',                           // block 2
		blocks: 3,
	},
	{
		label: 'B',
		key: '0000000000000000000000000000000000000000000000000000000000000000', // 256-bit all-zero key
		nonce: '00000000000000000000000000000000',
		pt: '000000000000000000000000000000000000000000000000' +
            '000000000000000000000000000000000000000000000000',
		ct: '8910494504181950F98DD998A82B6749' +                          // block 0 = ECB(zero-256,zero)
            '9FAA1E723BE36AA803321C2383DE86AD' +                          // block 1
            '0A3E7E267FBEF117CE63FCB3F0092CBC',                           // block 2
		blocks: 3,
	},
	{
		label: 'C',
		key: '00000000000000000000000000000000',                            // 128-bit all-zero key
		nonce: 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',                            // all-FF IV (counter wrap test)
		pt: 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF' +                          // 2 blocks all-FF PT
            'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
		ct: '1694760FECE869FDFA46403BF189B54D' +                         // block 0 (ctr=0xFF×16)
            '1645997D8947E7692F6C5619854EDFC9',                           // block 1 (ctr wrapped to 0x00×16)
		blocks: 2,
	},
	{
		label: 'D',
		key: '000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F', // 256-bit key
		nonce: '000102030405060708090A0B0C0D0E0F',
		pt: '000102030405060708090A0B0C0D0E0F' +
            '101112131415161718191A1B1C1D1E1F',
		ct: '64A81834E99AE14EA0477CDDF90076E1' +
            '78B4FA40E07C3157F13E8E77855C8EDA',
		blocks: 2,
	},
	{
		label: 'E',
		key: '000000000000000000000000000000000000000000000000', // 192-bit all-zero key
		nonce: '00000000000000000000000000000000',
		pt: '000000000000000000000000000000000000000000000000' +
            '000000000000000000000000000000000000000000000000',
		ct: '42046B25C85DBD6B402B296A97EF83A5' +
            '47402E1C09E0C315B13CAB5A5AA17E49' +
            '9DCAABB7839129739D1C6F5501624E44',
		blocks: 3,
	},
];
