//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
/**
 * CTR mode vectors — Serpent-CTR (self-generated)
 *
 * Source: Generated by ctr_harness.c built on floppy1 AES-submission reference.
 * https://github.com/xero/leviathan-crypto/tree/floppy1
 * Coverage: 5 cases (A–E): 128/256/192-bit keys, various IVs.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { init } from '../../../src/ts/index.js';
import { loadKey, fromHex, toHex, writeBytes, readBytes, getWasm } from '../helpers';
import { CTR_VECTORS } from '../../vectors/serpent_ctr.js';
import { serpentWasm } from '../../../src/ts/serpent/embedded.js';

beforeAll(async () => {
	await init({ serpent: serpentWasm });
});

describe('CTR mode — cross-check against leviathan 09_ctr_vectors.test.ts', () => {
	it('all 5 cases encrypt', () => {
		const wasm = getWasm();
		for (const { label, key, nonce, pt, ct } of CTR_VECTORS) {
			loadKey(key);
			writeBytes(fromHex(nonce), wasm.getNonceOffset());
			writeBytes(fromHex(pt), wasm.getChunkPtOffset());
			wasm.resetCounter();
			wasm.encryptChunk(pt.length / 2);
			const result = readBytes(wasm.getChunkCtOffset(), pt.length / 2);
			expect(toHex(result), `Case ${label} encrypt`).toBe(ct.toLowerCase());
		}
	});

	it('all 5 cases decrypt', () => {
		const wasm = getWasm();
		for (const { label, key, nonce, pt, ct } of CTR_VECTORS) {
			loadKey(key);
			writeBytes(fromHex(nonce), wasm.getNonceOffset());
			writeBytes(fromHex(ct), wasm.getChunkPtOffset());
			wasm.resetCounter();
			wasm.encryptChunk(ct.length / 2);
			const result = readBytes(wasm.getChunkCtOffset(), ct.length / 2);
			expect(toHex(result), `Case ${label} decrypt`).toBe(pt.toLowerCase());
		}
	});

	it('encrypt then decrypt round-trips correctly', () => {
		const wasm = getWasm();
		for (const { key, nonce, pt } of CTR_VECTORS) {
			const ptBytes = fromHex(pt);
			loadKey(key);
			writeBytes(fromHex(nonce), wasm.getNonceOffset());
			writeBytes(ptBytes, wasm.getChunkPtOffset());
			wasm.resetCounter();
			wasm.encryptChunk(ptBytes.length);
			const ct = readBytes(wasm.getChunkCtOffset(), ptBytes.length).slice();

			loadKey(key);
			writeBytes(fromHex(nonce), wasm.getNonceOffset());
			writeBytes(ct, wasm.getChunkPtOffset());
			wasm.resetCounter();
			wasm.encryptChunk(ct.length);
			const ptBack = readBytes(wasm.getChunkCtOffset(), ct.length);
			expect(toHex(ptBack)).toBe(pt.toLowerCase());
		}
	});

	it('counter increments — multi-block vectors have distinct blocks', () => {
		const cases3 = CTR_VECTORS.filter(v => v.blocks >= 3);
		for (const { ct } of cases3) {
			const b0 = ct.slice(0, 32).toLowerCase();
			const b1 = ct.slice(32, 64).toLowerCase();
			const b2 = ct.slice(64, 96).toLowerCase();
			expect(b0).not.toBe(b1);
			expect(b0).not.toBe(b2);
			expect(b1).not.toBe(b2);
		}
	});

	it('different nonces produce different ciphertext', () => {
		const wasm = getWasm();
		const v = CTR_VECTORS[0];
		const ptBytes = fromHex(v.pt);

		loadKey(v.key);
		writeBytes(fromHex(v.nonce), wasm.getNonceOffset());
		writeBytes(ptBytes, wasm.getChunkPtOffset());
		wasm.resetCounter();
		wasm.encryptChunk(ptBytes.length);
		const ct1 = toHex(readBytes(wasm.getChunkCtOffset(), ptBytes.length).slice());

		const altNonce = new Uint8Array(16); altNonce[15] = 0x01;
		loadKey(v.key);
		writeBytes(altNonce, wasm.getNonceOffset());
		writeBytes(ptBytes, wasm.getChunkPtOffset());
		wasm.resetCounter();
		wasm.encryptChunk(ptBytes.length);
		const ct2 = toHex(readBytes(wasm.getChunkCtOffset(), ptBytes.length));

		expect(ct1).not.toBe(ct2);
	});
});
