#!/usr/bin/env node
//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
// scripts/embed-workers.ts
//
// Bundles each pool-worker.ts into a self-contained IIFE and emits a TS
// file under src/ts/embedded/<cipher>-pool-worker.ts that exports the
// source as a string constant. Mirrors scripts/embed-wasm.ts.
//
// Why: the default new Worker(new URL('./pool-worker.js', import.meta.url))
// pattern triggers eager worker-chunk emission in Vite's transform hook,
// shipping orphan chunks for unused cipher suites (issue.md). Inlining
// the source as a tree-shakeable string export removes the pattern from
// the import graph. See issue2.md for the file:// regression that the
// classic-worker spawn site fixes.

import { build } from 'esbuild'
import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const OUT_DIR = resolve(ROOT, 'src/ts/embedded')

const HEADER =
	`// Generated by scripts/embed-workers.ts — do not edit\n`
	+ `// IIFE-bundled pool worker source. Spawned via blob URL by\n`
	+ `// the cipher-suite.ts createPoolWorker; consumers do not\n`
	+ `// import this directly.\n`
	+ `export const WORKER_SOURCE = `

const ciphers = [
	{ name: 'chacha20', entry: 'src/ts/chacha20/pool-worker.ts' },
	{ name: 'serpent',  entry: 'src/ts/serpent/pool-worker.ts'  },
]

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true })

for (const { name, entry } of ciphers) {
	const result = await build({
		entryPoints: [resolve(ROOT, entry)],
		bundle: true,
		minify: true,
		format: 'iife',
		target: 'es2022',
		platform: 'browser',
		write: false,
		legalComments: 'none',
	})
	const src = result.outputFiles[0].text
	const out = HEADER + JSON.stringify(src) + '\n'
	const outPath = resolve(OUT_DIR, `${name}-pool-worker.ts`)
	writeFileSync(outPath, out)
	console.log(`  ${entry} → embedded/${name}-pool-worker.ts  (${(src.length / 1024).toFixed(1)} KB IIFE)`)
}

console.log('All pool workers embedded successfully.')
