#!/usr/bin/env node
//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
/**
 * embed-wasm.ts
 *
 * Reads build/*.wasm and generates src/ts/embedded/*.ts files.
 * Each generated file exports a base64 string constant:
 *
 *   export const WASM_BASE64 = '...'
 *
 * These are build artifacts — gitignored. Regenerated on every build.
 * Used by the 'embedded' init() mode for zero-config WASM loading.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const BUILD_DIR = resolve(ROOT, 'build')
const OUT_DIR = resolve(ROOT, 'src/ts/embedded')

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true })

const modules = [
  { name: 'serpent', wasm: 'serpent.wasm' },
  { name: 'chacha',  wasm: 'chacha.wasm' },
  { name: 'sha2',    wasm: 'sha2.wasm' },
  { name: 'sha3',    wasm: 'sha3.wasm' },
]

for (const { name, wasm } of modules) {
  const wasmPath = resolve(BUILD_DIR, wasm)
  if (!existsSync(wasmPath)) {
    console.error(`Missing: ${wasmPath} — run build:asm first`)
    process.exit(1)
  }

  const binary = readFileSync(wasmPath)
  const b64 = binary.toString('base64')
  const outPath = resolve(OUT_DIR, `${name}.ts`)

  const content = `// Generated by scripts/embed-wasm.ts — do not edit\nexport const WASM_BASE64 = '${b64}'\n`
  writeFileSync(outPath, content)

  const kb = (binary.length / 1024).toFixed(1)
  const b64kb = (b64.length / 1024).toFixed(1)
  console.log(`  ${wasm} → embedded/${name}.ts  (${kb} KB binary → ${b64kb} KB base64)`)
}

console.log('All WASM modules embedded successfully.')

// ── Argon2id binaries (third-party, from node_modules) ──────────────────────
const ARGON2_DIR = resolve(ROOT, 'node_modules/argon2id/dist')

const argon2Modules = [
  { name: 'argon2id_simd',    wasm: 'simd.wasm' },
  { name: 'argon2id_nosimd',  wasm: 'no-simd.wasm' },
]

for (const { name, wasm } of argon2Modules) {
  const wasmPath = resolve(ARGON2_DIR, wasm)
  if (!existsSync(wasmPath)) {
    console.error(`Missing: ${wasmPath} — run bun install first`)
    process.exit(1)
  }

  const binary = readFileSync(wasmPath)
  const b64 = binary.toString('base64')
  const outPath = resolve(OUT_DIR, `${name}.ts`)

  const content = `// Generated by scripts/embed-wasm.ts — do not edit\nexport const WASM_BASE64 = '${b64}'\n`
  writeFileSync(outPath, content)

  const kb = (binary.length / 1024).toFixed(1)
  const b64kb = (b64.length / 1024).toFixed(1)
  console.log(`  ${wasm} → embedded/${name}.ts  (${kb} KB binary → ${b64kb} KB base64)`)
}

console.log('Argon2id binaries embedded successfully.')
