#!/usr/bin/env node
//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
// embed-wasm.ts
//
// Reads build/*.wasm and generates src/ts/embedded/*.ts files.
// Each generated file exports a gzip+base64 string constant:
//
//   export const WASM_GZ_BASE64 = '...'
//
// These are build artifacts are gitignored & regenerated on every build.
// Used by the 'embedded' init() mode for zero-config WASM loading.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { gzipSync } from 'zlib'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const BUILD_DIR = resolve(ROOT, 'build')
const OUT_DIR = resolve(ROOT, 'src/ts/embedded')

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true })

const modules = [
  { name: 'serpent', wasm: 'serpent.wasm' },
  { name: 'chacha20', wasm: 'chacha20.wasm' },
  { name: 'sha2',    wasm: 'sha2.wasm' },
  { name: 'sha3',    wasm: 'sha3.wasm' },
]

for (const { name, wasm } of modules) {
  const wasmPath = resolve(BUILD_DIR, wasm)
  if (!existsSync(wasmPath)) {
    console.error(`Missing: ${wasmPath} — run build:asm first`)
    process.exit(1)
  }

  const binary = readFileSync(wasmPath)
  const compressed = gzipSync(binary)
  compressed[4] = compressed[5] = compressed[6] = compressed[7] = 0
  const b64 = compressed.toString('base64')
  const outPath = resolve(OUT_DIR, `${name}.ts`)

  const content = `// Generated by scripts/embed-wasm.ts — do not edit\n// gzip-compressed WASM binary, base64-encoded. Decoded and decompressed by loadEmbedded().\nexport const WASM_GZ_BASE64 = '${b64}'\n`
  writeFileSync(outPath, content)

  const kb = (binary.length / 1024).toFixed(1)
  const gzKb = (compressed.length / 1024).toFixed(1)
  const b64kb = (b64.length / 1024).toFixed(1)
  console.log(`  ${wasm} → embedded/${name}.ts  (${kb} KB → ${gzKb} KB gzip → ${b64kb} KB base64)`)
}

// CT module: raw byte array (too small for gzip+base64 — raw is smaller)
const ctWasmPath = resolve(BUILD_DIR, 'ct.wasm')
if (!existsSync(ctWasmPath)) {
  console.error(`Missing: ${ctWasmPath} — run build:asm first`)
  process.exit(1)
}
const ctBytes = readFileSync(ctWasmPath)
const ctLiteral = `new Uint8Array([${Array.from(ctBytes).join(',')}])`
const ctOutPath = resolve(ROOT, 'src/ts/ct-wasm.ts')
writeFileSync(ctOutPath,
  `// auto-generated — do not edit\n// raw WASM bytes for constant-time comparison module\nexport const CT_WASM = ${ctLiteral};\n`)
console.log(`  ct.wasm → src/ts/ct-wasm.ts  (${ctBytes.length} bytes raw)`)

console.log('All WASM modules embedded successfully.')
