// scripts/gen-hybrid-pq-vectors.ts
//
// One-shot generator for test/vectors/sign_hybrid_pq.ts. Builds locking
// envelope-wire-format vectors for the three PQ-only hybrid suites
// (0x30 / 0x31 / 0x32) using deterministic sub-sign on both halves so the
// composite signature bytes are byte-stable across runs. Run as:
//   bun scripts/gen-hybrid-pq-vectors.ts
// then commit the regenerated vectors file.

import {init, bytesToHex, hexToBytes, concat, utf8ToBytes} from '../src/ts/index.js'
import {mldsaWasm} from '../src/ts/mldsa/embedded.js'
import {slhdsaWasm} from '../src/ts/slhdsa/embedded.js'
import {sha3Wasm} from '../src/ts/sha3/embedded.js'
import {
	MlDsa44,
	MlDsa65,
	MlDsa87,
	MLDSA44,
	MLDSA65,
	MLDSA87,
} from '../src/ts/mldsa/index.js'
import type {MlDsaParams} from '../src/ts/mldsa/index.js'
import {
	SlhDsa128f,
	SlhDsa192f,
	SlhDsa256f,
	SLHDSA128F,
	SLHDSA192F,
	SLHDSA256F,
} from '../src/ts/slhdsa/index.js'
import type {SlhDsaParams} from '../src/ts/slhdsa/index.js'
import {
	MlDsa44SlhDsa128fSuite,
	MlDsa65SlhDsa192fSuite,
	MlDsa87SlhDsa256fSuite,
} from '../src/ts/sign/index.js'
import type {StreamableSignatureSuite} from '../src/ts/sign/index.js'
import {buildEffectiveCtx} from '../src/ts/sign/ctx.js'
import {SHAKE128, SHAKE256} from '../src/ts/sha3/index.js'
import {writeFileSync} from 'node:fs'

await init({mldsa: mldsaWasm, slhdsa: slhdsaWasm, sha3: sha3Wasm})

const HEADER = `//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
// test/vectors/sign_hybrid_pq.ts
//
// Composite KAT vectors locking the v3 attached envelope wire format
// produced by the three PQ-only hybrid suites (MlDsa{44,65,87}SlhDsa{128f,
// 192f,256f}Suite). Sigs are generated by driving the underlying primitive
// classes' deterministic prehashed sign paths on both halves
// (signHashPrehashedDeterministic) and concatenating
// sig_mldsa || sig_slhdsa, matching what the suite's hedged sign path
// produces structurally but with byte-stable bytes for KAT replay.
//
// Audit status: SELF-GENERATED (wire-format gate). No composite-sigs draft
// covers PQ-only ML-DSA || SLH-DSA pairs, so these vectors are anchored
// to the leviathan-defined wire format documented in docs/signaturesuite.md.
//
// Inputs per record:
//   mldsaSeedHex   32-byte hex seed fed to MlDsa{44,65,87}.keygenDerand.
//   slhdsaSeedHex  3·n-byte hex seed fed to SlhDsa{128f,192f,256f}.keygenDerand.
//   pkHex          pk_combined = pk_mldsa || pk_slhdsa.
//   skHex          sk_combined = sk_mldsa || sk_slhdsa.
//   msgHex         payload bytes (UTF-8 of the per-record message string).
//   ctxHex         user_ctx bytes (UTF-8 of "v3-suite-kat").
//   blobHex        attached envelope: [formatEnum, ctxLen, ctx, payload, sig].
//
// All hex strings are lowercase, no separators.

`

type MlClass = typeof MlDsa44 | typeof MlDsa65 | typeof MlDsa87
type SlhClass = typeof SlhDsa128f | typeof SlhDsa192f | typeof SlhDsa256f

interface HybridSpec {
	id: string
	description: string
	formatEnum: number
	suite: StreamableSignatureSuite
	MlDsaClass: MlClass
	mldsaParams: MlDsaParams
	SlhDsaClass: SlhClass
	slhdsaParams: SlhDsaParams
	prehashAlgorithm: 'shake-128' | 'shake-256'
	prehashName: 'SHAKE128' | 'SHAKE256'
	prehashSize: number
	msg: string
}

const SPECS: HybridSpec[] = [
	{
		id: 'V1',
		description: 'V1, ML-DSA-44 || SLH-DSA-128f (cat-1, SHAKE128 prehash)',
		formatEnum: 0x30,
		suite: MlDsa44SlhDsa128fSuite,
		MlDsaClass: MlDsa44, mldsaParams: MLDSA44,
		SlhDsaClass: SlhDsa128f, slhdsaParams: SLHDSA128F,
		prehashAlgorithm: 'shake-128',
		prehashName: 'SHAKE128', prehashSize: 32,
		msg: 'leviathan-crypto mldsa44-slhdsa128f hybrid',
	},
	{
		id: 'V2',
		description: 'V2, ML-DSA-65 || SLH-DSA-192f (cat-3, SHAKE256 prehash)',
		formatEnum: 0x31,
		suite: MlDsa65SlhDsa192fSuite,
		MlDsaClass: MlDsa65, mldsaParams: MLDSA65,
		SlhDsaClass: SlhDsa192f, slhdsaParams: SLHDSA192F,
		prehashAlgorithm: 'shake-256',
		prehashName: 'SHAKE256', prehashSize: 64,
		msg: 'leviathan-crypto mldsa65-slhdsa192f hybrid',
	},
	{
		id: 'V3',
		description: 'V3, ML-DSA-87 || SLH-DSA-256f (cat-5, SHAKE256 prehash)',
		formatEnum: 0x32,
		suite: MlDsa87SlhDsa256fSuite,
		MlDsaClass: MlDsa87, mldsaParams: MLDSA87,
		SlhDsaClass: SlhDsa256f, slhdsaParams: SLHDSA256F,
		prehashAlgorithm: 'shake-256',
		prehashName: 'SHAKE256', prehashSize: 64,
		msg: 'leviathan-crypto mldsa87-slhdsa256f hybrid',
	},
]

function mldsaSeed(byte: number): Uint8Array {
	return new Uint8Array(32).fill(byte)
}
function slhSeed(params: SlhDsaParams, byte: number): Uint8Array {
	return new Uint8Array(3 * params.n).fill(byte)
}
function shake(algo: 'SHAKE128' | 'SHAKE256', msg: Uint8Array, outLen: number): Uint8Array {
	const h = algo === 'SHAKE128' ? new SHAKE128() : new SHAKE256()
	try {
		return h.hash(msg, outLen)
	} finally {
		h.dispose()
	}
}
function assembleBlob(suiteByte: number, ctx: Uint8Array, payload: Uint8Array, sig: Uint8Array): Uint8Array {
	const out = new Uint8Array(2 + ctx.length + payload.length + sig.length)
	let pos = 0
	out[pos++] = suiteByte
	out[pos++] = ctx.length
	out.set(ctx, pos); pos += ctx.length
	out.set(payload, pos); pos += payload.length
	out.set(sig, pos)
	return out
}
function chunkHex(hex: string, perLine = 64): string {
	const parts: string[] = []
	for (let i = 0; i < hex.length; i += perLine) parts.push(hex.slice(i, i + perLine))
	return parts.map((p, i) => `\t\t\t\t'${p}'${i === parts.length - 1 ? '' : ' +'}`).join('\n')
}
const recordHexLine = (label: string, hex: string): string => {
	if (hex.length <= 64) return `\t\t${label}: '${hex}',`
	return `\t\t${label}:\n${chunkHex(hex)},`
}

const CTX = utf8ToBytes('v3-suite-kat')

const records: string[] = []
let mldsaSeedByte = 0xaa
let slhdsaSeedByte = 0x55
for (const spec of SPECS) {
	const xi = mldsaSeed(mldsaSeedByte++)
	const slhSeedBytes = slhSeed(spec.slhdsaParams, slhdsaSeedByte++)

	// Generate both halves' keys via deterministic seeds.
	const mldsaInst = new spec.MlDsaClass()
	let mldsaKp: {verificationKey: Uint8Array; signingKey: Uint8Array}
	try {
		mldsaKp = mldsaInst.keygenDerand(xi)
	} finally {
		mldsaInst.dispose()
	}
	const slhInst = new spec.SlhDsaClass()
	let slhKp: {verificationKey: Uint8Array; signingKey: Uint8Array}
	try {
		slhKp = slhInst.keygenDerand(slhSeedBytes)
	} finally {
		slhInst.dispose()
	}

	const pkCombined = concat(mldsaKp.verificationKey, slhKp.verificationKey)
	const skCombined = concat(mldsaKp.signingKey, slhKp.signingKey)

	// Compute the shared prehash digest and effective_ctx exactly as the
	// hybrid suite would internally.
	const msgBytes = utf8ToBytes(spec.msg)
	const digest = shake(spec.prehashName, msgBytes, spec.prehashSize)
	const effectiveCtx = buildEffectiveCtx(spec.suite.ctxDomain, CTX)

	// Drive each half's deterministic prehashed sign for byte-stable output.
	const mldsaInst2 = new spec.MlDsaClass()
	let sigMldsa: Uint8Array
	try {
		sigMldsa = mldsaInst2.signHashPrehashedDeterministic(
			mldsaKp.signingKey, digest, spec.prehashName, effectiveCtx,
		)
	} finally {
		mldsaInst2.dispose()
	}
	const slhInst2 = new spec.SlhDsaClass()
	let sigSlh: Uint8Array
	try {
		sigSlh = slhInst2.signHashPrehashedDeterministic(
			slhKp.signingKey, digest, spec.prehashName, effectiveCtx,
		)
	} finally {
		slhInst2.dispose()
	}

	const sigCombined = concat(sigMldsa, sigSlh)
	const blob = assembleBlob(spec.formatEnum, CTX, msgBytes, sigCombined)

	// Size sanity: catalog-known.
	const expectedPkSize = spec.mldsaParams.pkBytes + spec.slhdsaParams.pkBytes
	const expectedSkSize = spec.mldsaParams.skBytes + spec.slhdsaParams.skBytes
	const expectedSigSize = spec.mldsaParams.sigBytes + spec.slhdsaParams.sigBytes
	if (pkCombined.length !== expectedPkSize)
		throw new Error(`${spec.id}: pk size mismatch ${pkCombined.length} != ${expectedPkSize}`)
	if (skCombined.length !== expectedSkSize)
		throw new Error(`${spec.id}: sk size mismatch ${skCombined.length} != ${expectedSkSize}`)
	if (sigCombined.length !== expectedSigSize)
		throw new Error(`${spec.id}: sig size mismatch ${sigCombined.length} != ${expectedSigSize}`)

	// Sanity-check via the suite verify path.
	const ok = spec.suite.verify(pkCombined, msgBytes, sigCombined, CTX)
	if (!ok) throw new Error(`${spec.id}: suite.verify rejected freshly-generated sig`)

	records.push(`\t{
\t\tid: '${spec.id}',
\t\tdescription: '${spec.description}',
\t\tformatEnum: 0x${spec.formatEnum.toString(16).padStart(2, '0')},
\t\tprehashAlgorithm: '${spec.prehashAlgorithm}',
${recordHexLine('mldsaSeedHex', bytesToHex(xi))}
${recordHexLine('slhdsaSeedHex', bytesToHex(slhSeedBytes))}
${recordHexLine('pkHex', bytesToHex(pkCombined))}
${recordHexLine('skHex', bytesToHex(skCombined))}
${recordHexLine('msgHex', bytesToHex(msgBytes))}
${recordHexLine('ctxHex', bytesToHex(CTX))}
${recordHexLine('blobHex', bytesToHex(blob))}
\t},`)

	const reparsed = hexToBytes(bytesToHex(blob))
	if (reparsed.length !== blob.length) throw new Error(`${spec.id}: round-trip length mismatch`)
}

const file =
	HEADER +
	`export interface SignHybridPqVector {
\tid:                string;
\tdescription:       string;
\tformatEnum:        number;
\tprehashAlgorithm:  'shake-128' | 'shake-256';
\tmldsaSeedHex:      string;
\tslhdsaSeedHex:     string;
\tpkHex:             string;
\tskHex:             string;
\tmsgHex:            string;
\tctxHex:            string;
\tblobHex:           string;
}

export const signHybridPqVectors: SignHybridPqVector[] = [
${records.join('\n')}
];
`

writeFileSync('test/vectors/sign_hybrid_pq.ts', file)
console.log('Wrote test/vectors/sign_hybrid_pq.ts with', SPECS.length, 'records')
