//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
import type { Module } from './init.js';

// Embedded base64-encoded WASM binaries (generated by scripts/embed-wasm.ts)
const embeddedLoaders: Record<Module, () => Promise<string>> = {
	serpent: () => import('./embedded/serpent.js').then(m => m.WASM_BASE64),
	chacha20: () => import('./embedded/chacha.js').then(m => m.WASM_BASE64),
	sha2: () => import('./embedded/sha2.js').then(m => m.WASM_BASE64),
	sha3: () => import('./embedded/sha3.js').then(m => m.WASM_BASE64),
};

function base64ToBytes(b64: string): Uint8Array {
	if (typeof atob === 'function') {
		const raw = atob(b64);
		const out = new Uint8Array(raw.length);
		for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
		return out;
	}
	return new Uint8Array(Buffer.from(b64, 'base64'));
}

async function instantiateFromBytes(
	bytes: Uint8Array,
): Promise<WebAssembly.Instance> {
	const result = await WebAssembly.instantiate(
    bytes.buffer as ArrayBuffer,
    { env: { memory: new WebAssembly.Memory({ initial: 3, maximum: 3 }) } },
	);
	return result.instance;
}

export async function loadEmbedded(mod: Module): Promise<WebAssembly.Instance> {
	const b64 = await embeddedLoaders[mod]();
	const bytes = base64ToBytes(b64);
	return instantiateFromBytes(bytes);
}

export async function loadStreaming(
	_mod: Module,
	baseUrl: URL | string,
	filename: string,
): Promise<WebAssembly.Instance> {
	const url = new URL(filename, baseUrl).href;
	const result = await WebAssembly.instantiateStreaming(fetch(url), {
		env: { memory: new WebAssembly.Memory({ initial: 3, maximum: 3 }) },
	});
	return result.instance;
}

export async function loadManual(
	binary: Uint8Array | ArrayBuffer,
): Promise<WebAssembly.Instance> {
	const bytes = binary instanceof ArrayBuffer ? new Uint8Array(binary) : binary;
	return instantiateFromBytes(bytes);
}
