//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
/**
 * SealStream AES-GCM-SIV v3 Known-Answer Tests (KAT).
 *
 * Pinned vectors generated by `scripts/gen-sealstream-vectors.ts --cipher aes`.
 * Each vector was independently verified at generation time against the
 * raw AES-GCM-SIV WASM ops (sivAeadEncrypt) and HKDF-SHA-256. These tests
 * detect accidental wire format changes.
 *
 * v3 wire format: 20-byte header + 32-byte key commitment in the preamble
 * (52 bytes total). HKDF info string binds the full header.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { init, hexToBytes, bytesToHex } from '../../../src/ts/index.js';
import { SealStream, OpenStream } from '../../../src/ts/stream/index.js';
import { AESGCMSIVCipher } from '../../../src/ts/aes/cipher-suite.js';
import { aesWasm } from '../../../src/ts/aes/embedded.js';
import { sha2Wasm } from '../../../src/ts/sha2/embedded.js';
import { ac1, ac3, acf1 } from '../../vectors/sealstream_aes_v3.js';
import type { SealStreamAesV3Vector } from '../../vectors/sealstream_aes_v3.js';

beforeAll(async () => {
	await init({ aes: aesWasm, sha2: sha2Wasm });
});

function toHex(b: Uint8Array): string {
	return bytesToHex(b);
}

function runKAT(name: string, v: SealStreamAesV3Vector): void {
	describe(`KAT: ${name}`, () => {
		const key = hexToBytes(v.key);
		const nonce = hexToBytes(v.nonce);

		const opts = { chunkSize: v.chunkSize, framed: v.framed };

		it('preamble (header + commitment, 52 bytes) matches pinned hex', () => {
			const sealer = SealStream._fromNonce(AESGCMSIVCipher, key, opts, nonce);
			expect(toHex(sealer.preamble)).toBe(v.preamble);
			sealer.finalize(new Uint8Array(0)); // clean up
		});

		it('seal output matches pinned ciphertext per chunk', () => {
			const sealer = SealStream._fromNonce(AESGCMSIVCipher, key, opts, nonce);
			for (let i = 0; i < v.chunks.length; i++) {
				const pt = hexToBytes(v.chunks[i].plaintext);
				const isLast = i === v.chunks.length - 1;
				const ct = isLast ? sealer.finalize(pt) : sealer.push(pt);
				expect(toHex(ct)).toBe(v.chunks[i].ciphertext);
			}
		});

		it('round-trip through OpenStream', () => {
			const sealer = SealStream._fromNonce(AESGCMSIVCipher, key, opts, nonce);
			const preamble = sealer.preamble;
			const cts: Uint8Array[] = [];
			for (let i = 0; i < v.chunks.length; i++) {
				const pt = hexToBytes(v.chunks[i].plaintext);
				const isLast = i === v.chunks.length - 1;
				cts.push(isLast ? sealer.finalize(pt) : sealer.push(pt));
			}

			const opener = new OpenStream(AESGCMSIVCipher, key, preamble);
			for (let i = 0; i < cts.length; i++) {
				const isLast = i === cts.length - 1;
				const pt = isLast ? opener.finalize(cts[i]) : opener.pull(cts[i]);
				expect(toHex(pt)).toBe(v.chunks[i].plaintext);
			}
		});
	});
}

runKAT('AC1 (aes-gcm-siv v3 single-chunk)', ac1);
runKAT('AC3 (aes-gcm-siv v3 multi-chunk)', ac3);
runKAT('ACF1 (aes-gcm-siv v3 framed)', acf1);
