//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
/**
 * Seal XChaCha20 v3 Known-Answer Tests (KAT).
 *
 * Pinned vectors generated by `scripts/gen-seal-vectors.ts --cipher xchacha`.
 * Each vector was independently verified against raw primitives at
 * generation time. These tests detect accidental wire format changes.
 *
 * v3 wire format: 20-byte header + 32-byte key commitment in the preamble
 * (52 bytes total). HKDF info string binds the full header.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { init, hexToBytes, bytesToHex } from '../../../src/ts/index.js';
import { Seal, OpenStream, HEADER_SIZE } from '../../../src/ts/stream/index.js';
import { XChaCha20Cipher } from '../../../src/ts/chacha20/cipher-suite.js';
import { chacha20Wasm } from '../../../src/ts/chacha20/embedded.js';
import { sha2Wasm } from '../../../src/ts/sha2/embedded.js';
import { xc1, xc_empty } from '../../vectors/seal_xchacha_v3.js';
import type { SealXChachaV3Vector } from '../../vectors/seal_xchacha_v3.js';

beforeAll(async () => {
	await init({ chacha20: chacha20Wasm, sha2: sha2Wasm });
});

const PREAMBLE_LEN = HEADER_SIZE + XChaCha20Cipher.commitmentSize;  // 52 bytes

function toHex(b: Uint8Array): string {
	return bytesToHex(b);
}

function runKAT(name: string, v: SealXChachaV3Vector): void {
	describe(`KAT: ${name}`, () => {
		const key   = hexToBytes(v.key);
		const nonce = hexToBytes(v.nonce);
		const pt    = hexToBytes(v.plaintext);

		it('blob matches pinned hex', () => {
			const blob = Seal._fromNonce(XChaCha20Cipher, key, pt, nonce);
			expect(toHex(blob)).toBe(v.blob);
		});

		it('preamble (header + commitment, 52 bytes) matches pinned hex', () => {
			const blob = Seal._fromNonce(XChaCha20Cipher, key, pt, nonce);
			expect(toHex(blob.subarray(0, PREAMBLE_LEN))).toBe(v.preamble);
		});

		it('header byte 0 carries v3 format enum 0x03', () => {
			const blob = Seal._fromNonce(XChaCha20Cipher, key, pt, nonce);
			expect(blob[0] & 0x3f).toBe(0x03);
		});

		it('Seal.decrypt recovers plaintext', () => {
			const blob = hexToBytes(v.blob);
			const out  = Seal.decrypt(XChaCha20Cipher, key, blob);
			expect(toHex(out)).toBe(v.plaintext);
		});

		it('OpenStream.finalize recovers plaintext (unified format)', () => {
			const blob     = hexToBytes(v.blob);
			const preamble = blob.subarray(0, PREAMBLE_LEN);
			const opener   = new OpenStream(XChaCha20Cipher, key, preamble);
			const out      = opener.finalize(blob.subarray(PREAMBLE_LEN));
			expect(toHex(out)).toBe(v.plaintext);
		});
	});
}

runKAT('xc1 (xchacha20 v3, 100B)', xc1);
runKAT('xc_empty (xchacha20 v3, empty)', xc_empty);
