//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
/**
 * SealStream Serpent v3 Known-Answer Tests (KAT).
 *
 * Pinned vectors generated by `scripts/gen-sealstream-vectors.ts --cipher serpent`.
 * Each vector was independently verified against raw primitives at
 * generation time. These tests detect accidental wire format changes.
 *
 * v3 wire format: 20-byte header preamble. HMAC-SHA-256 chunk
 * authentication is collision-resistant under SHA-256, which is
 * key-committing, no separate commitment is needed in the preamble.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { init, hexToBytes, bytesToHex } from '../../../src/ts/index.js';
import { SealStream, OpenStream } from '../../../src/ts/stream/index.js';
import { SerpentCipher } from '../../../src/ts/serpent/cipher-suite.js';
import { serpentWasm } from '../../../src/ts/serpent/embedded.js';
import { sha2Wasm } from '../../../src/ts/sha2/embedded.js';
import { sc1, sc3, scf1 } from '../../vectors/sealstream_serpent_v3.js';
import type { SealStreamSerpentV3Vector } from '../../vectors/sealstream_serpent_v3.js';

beforeAll(async () => {
	await init({ serpent: serpentWasm, sha2: sha2Wasm });
});

function toHex(b: Uint8Array): string {
	return bytesToHex(b);
}

function runKAT(name: string, v: SealStreamSerpentV3Vector): void {
	describe(`KAT: ${name}`, () => {
		const key = hexToBytes(v.key);
		const nonce = hexToBytes(v.nonce);

		const opts = { chunkSize: v.chunkSize, framed: v.framed };

		it('preamble (header, 20 bytes) matches pinned hex', () => {
			const sealer = SealStream._fromNonce(SerpentCipher, key, opts, nonce);
			expect(toHex(sealer.preamble)).toBe(v.preamble);
			sealer.finalize(new Uint8Array(0)); // clean up
		});

		it('seal output matches pinned ciphertext per chunk', () => {
			const sealer = SealStream._fromNonce(SerpentCipher, key, opts, nonce);
			for (let i = 0; i < v.chunks.length; i++) {
				const pt = hexToBytes(v.chunks[i].plaintext);
				const isLast = i === v.chunks.length - 1;
				const ct = isLast ? sealer.finalize(pt) : sealer.push(pt);
				expect(toHex(ct)).toBe(v.chunks[i].ciphertext);
			}
		});

		it('round-trip through OpenStream', () => {
			const sealer = SealStream._fromNonce(SerpentCipher, key, opts, nonce);
			const preamble = sealer.preamble;
			const cts: Uint8Array[] = [];
			for (let i = 0; i < v.chunks.length; i++) {
				const pt = hexToBytes(v.chunks[i].plaintext);
				const isLast = i === v.chunks.length - 1;
				cts.push(isLast ? sealer.finalize(pt) : sealer.push(pt));
			}

			const opener = new OpenStream(SerpentCipher, key, preamble);
			for (let i = 0; i < cts.length; i++) {
				const isLast = i === cts.length - 1;
				const pt = isLast ? opener.finalize(cts[i]) : opener.pull(cts[i]);
				expect(toHex(pt)).toBe(v.chunks[i].plaintext);
			}
		});
	});
}

runKAT('SC1 (serpent v3 single-chunk)', sc1);
runKAT('SC3 (serpent v3 multi-chunk)', sc3);
runKAT('SCF1 (serpent v3 framed)', scf1);
