//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
/**
 * Seal Serpent v2 Known-Answer Tests (KAT).
 *
 * Pinned vectors generated by `scripts/gen-seal-vectors.ts --cipher serpent`.
 * Each vector was independently verified against raw primitives at
 * generation time. These tests detect accidental wire format changes.
 *
 * v2 wire format: 20-byte header preamble. HMAC-SHA-256 chunk
 * authentication is collision-resistant under SHA-256, which is
 * key-committing — no separate commitment is needed in the preamble.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { init, hexToBytes, bytesToHex } from '../../../src/ts/index.js';
import { Seal, OpenStream, HEADER_SIZE } from '../../../src/ts/stream/index.js';
import { SerpentCipher } from '../../../src/ts/serpent/cipher-suite.js';
import { serpentWasm } from '../../../src/ts/serpent/embedded.js';
import { sha2Wasm } from '../../../src/ts/sha2/embedded.js';
import { sc1, sc_empty } from '../../vectors/seal_serpent_v2.js';
import type { SealSerpentV2Vector } from '../../vectors/seal_serpent_v2.js';

beforeAll(async () => {
	await init({ serpent: serpentWasm, sha2: sha2Wasm });
});

function toHex(b: Uint8Array): string {
	return bytesToHex(b);
}

function runKAT(name: string, v: SealSerpentV2Vector): void {
	describe(`KAT: ${name}`, () => {
		const key   = hexToBytes(v.key);
		const nonce = hexToBytes(v.nonce);
		const pt    = hexToBytes(v.plaintext);

		it('blob matches pinned hex', () => {
			const blob = Seal._fromNonce(SerpentCipher, key, pt, nonce);
			expect(toHex(blob)).toBe(v.blob);
		});

		it('preamble (header, 20 bytes) matches pinned hex', () => {
			const blob = Seal._fromNonce(SerpentCipher, key, pt, nonce);
			expect(toHex(blob.subarray(0, HEADER_SIZE))).toBe(v.preamble);
		});

		it('header byte 0 carries v2 format enum 0x02', () => {
			const blob = Seal._fromNonce(SerpentCipher, key, pt, nonce);
			expect(blob[0] & 0x3f).toBe(0x02);
		});

		it('Seal.decrypt recovers plaintext', () => {
			const blob = hexToBytes(v.blob);
			const out  = Seal.decrypt(SerpentCipher, key, blob);
			expect(toHex(out)).toBe(v.plaintext);
		});

		it('OpenStream.finalize recovers plaintext (unified format)', () => {
			const blob     = hexToBytes(v.blob);
			const preamble = blob.subarray(0, HEADER_SIZE);
			const opener   = new OpenStream(SerpentCipher, key, preamble);
			const out      = opener.finalize(blob.subarray(HEADER_SIZE));
			expect(toHex(out)).toBe(v.plaintext);
		});
	});
}

runKAT('sc1 (serpent v2, 100B)', sc1);
runKAT('sc_empty (serpent v2, empty)', sc_empty);
