//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
/**
 * SealStream v2 Known-Answer Tests (KAT).
 *
 * Pinned vectors generated by scripts/gen-sealstream-vectors.ts.
 * Each vector was independently verified against raw primitives at
 * generation time. These tests detect accidental wire format changes.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { init, hexToBytes, bytesToHex } from '../../../src/ts/index.js';
import { SealStream, OpenStream } from '../../../src/ts/stream/index.js';
import { XChaCha20Cipher } from '../../../src/ts/chacha20/cipher-suite.js';
import { SerpentCipher } from '../../../src/ts/serpent/cipher-suite.js';
import { chacha20Wasm } from '../../../src/ts/chacha20/embedded.js';
import { serpentWasm } from '../../../src/ts/serpent/embedded.js';
import { sha2Wasm } from '../../../src/ts/sha2/embedded.js';
import type { CipherSuite } from '../../../src/ts/stream/types.js';
import { xc1, xc3, sc1, sc3, xcf1, scf1 } from '../../vectors/sealstream_v2.js';
import type { SealStreamV2Vector } from '../../vectors/sealstream_v2.js';

beforeAll(async () => {
	await init({ chacha20: chacha20Wasm, serpent: serpentWasm, sha2: sha2Wasm });
});

function toHex(b: Uint8Array): string {
	return bytesToHex(b);
}

function cipherFor(v: SealStreamV2Vector): CipherSuite {
	return v.cipher === 'xchacha20' ? XChaCha20Cipher : SerpentCipher;
}

function runKAT(name: string, v: SealStreamV2Vector): void {
	describe(`KAT: ${name}`, () => {
		const cipher = cipherFor(v);
		const key = hexToBytes(v.key);
		const nonce = hexToBytes(v.nonce);

		const opts = { chunkSize: v.chunkSize, framed: v.framed };

		it('preamble matches pinned hex', () => {
			const sealer = SealStream._fromNonce(cipher, key, opts, nonce);
			expect(toHex(sealer.preamble)).toBe(v.preamble);
			sealer.finalize(new Uint8Array(0)); // clean up
		});

		it('seal output matches pinned ciphertext per chunk', () => {
			const sealer = SealStream._fromNonce(cipher, key, opts, nonce);
			for (let i = 0; i < v.chunks.length; i++) {
				const pt = hexToBytes(v.chunks[i].plaintext);
				const isLast = i === v.chunks.length - 1;
				const ct = isLast ? sealer.finalize(pt) : sealer.push(pt);
				expect(toHex(ct)).toBe(v.chunks[i].ciphertext);
			}
		});

		it('round-trip through OpenStream', () => {
			const sealer = SealStream._fromNonce(cipher, key, opts, nonce);
			const preamble = sealer.preamble;
			const cts: Uint8Array[] = [];
			for (let i = 0; i < v.chunks.length; i++) {
				const pt = hexToBytes(v.chunks[i].plaintext);
				const isLast = i === v.chunks.length - 1;
				cts.push(isLast ? sealer.finalize(pt) : sealer.push(pt));
			}

			const opener = new OpenStream(cipher, key, preamble);
			for (let i = 0; i < cts.length; i++) {
				const isLast = i === cts.length - 1;
				const pt = isLast ? opener.finalize(cts[i]) : opener.pull(cts[i]);
				expect(toHex(pt)).toBe(v.chunks[i].plaintext);
			}
		});
	});
}

runKAT('XC1 (xchacha20 single-chunk)', xc1);
runKAT('XC3 (xchacha20 multi-chunk)', xc3);
runKAT('SC1 (serpent single-chunk)', sc1);
runKAT('SC3 (serpent multi-chunk)', sc3);
runKAT('XCF1 (xchacha20 framed)', xcf1);
runKAT('SCF1 (serpent framed)', scf1);
