//                  ▄▄▄▄▄▄▄▄▄▄
//           ▄████████████████████▄▄          ▒  ▄▀▀ ▒ ▒ █ ▄▀▄ ▀█▀ █ ▒ ▄▀▄ █▀▄
//        ▄██████████████████████ ▀████▄      ▓  ▓▀  ▓ ▓ ▓ ▓▄▓  ▓  ▓▀▓ ▓▄▓ ▓ ▓
//      ▄█████████▀▀▀     ▀███████▄▄███████▌  ▀▄ ▀▄▄ ▀▄▀ ▒ ▒ ▒  ▒  ▒ █ ▒ ▒ ▒ █
//     ▐████████▀   ▄▄▄▄     ▀████████▀██▀█▌
//     ████████      ███▀▀     ████▀  █▀ █▀       Leviathan Crypto Library
//     ███████▌    ▀██▀         ███
//      ███████   ▀███           ▀██ ▀█▄      Repository & Mirror:
//       ▀██████   ▄▄██            ▀▀  ██▄    github.com/xero/leviathan-crypto
//         ▀█████▄   ▄██▄             ▄▀▄▀    unpkg.com/leviathan-crypto
//            ▀████▄   ▄██▄
//              ▐████   ▐███                  Author: xero (https://x-e.ro)
//       ▄▄██████████    ▐███         ▄▄      License: MIT
//    ▄██▀▀▀▀▀▀▀▀▀▀     ▄████      ▄██▀
//  ▄▀  ▄▄█████████▄▄  ▀▀▀▀▀     ▄███         This file is provided completely
//   ▄██████▀▀▀▀▀▀██████▄ ▀▄▄▄▄████▀          free, "as is", and without
//  ████▀    ▄▄▄▄▄▄▄ ▀████▄ ▀█████▀  ▄▄▄▄     warranty of any kind. The author
//  █████▄▄█████▀▀▀▀▀▀▄ ▀███▄      ▄████      assumes absolutely no liability
//   ▀██████▀             ▀████▄▄▄████▀       for its {ab,mis,}use.
//                           ▀█████▀▀
//
/**
 * Seal v2 Known-Answer Tests (KAT).
 *
 * Pinned vectors generated by scripts/gen-seal-vectors.ts.
 * Each vector was independently verified against raw primitives at
 * generation time. These tests detect accidental wire format changes.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { init, hexToBytes, bytesToHex } from '../../../src/ts/index.js';
import { Seal, OpenStream, HEADER_SIZE } from '../../../src/ts/stream/index.js';
import { XChaCha20Cipher } from '../../../src/ts/chacha20/cipher-suite.js';
import { SerpentCipher } from '../../../src/ts/serpent/cipher-suite.js';
import { chacha20Wasm } from '../../../src/ts/chacha20/embedded.js';
import { serpentWasm } from '../../../src/ts/serpent/embedded.js';
import { sha2Wasm } from '../../../src/ts/sha2/embedded.js';
import { xc1, xc_empty, sc1, sc_empty } from '../../vectors/seal_v2.js';
import type { SealV2Vector } from '../../vectors/seal_v2.js';

beforeAll(async () => {
	await init({ chacha20: chacha20Wasm, serpent: serpentWasm, sha2: sha2Wasm });
});

function toHex(b: Uint8Array): string {
	return bytesToHex(b);
}

function runKAT(name: string, v: SealV2Vector): void {
	describe(`KAT: ${name}`, () => {
		const cipher = v.cipher === 'xchacha20' ? XChaCha20Cipher : SerpentCipher;
		const key    = hexToBytes(v.key);
		const nonce  = hexToBytes(v.nonce);
		const pt     = hexToBytes(v.plaintext);

		it('blob matches pinned hex', () => {
			const blob = Seal._fromNonce(cipher, key, pt, nonce);
			expect(toHex(blob)).toBe(v.blob);
		});

		it('preamble (first 20 bytes) matches pinned hex', () => {
			const blob = Seal._fromNonce(cipher, key, pt, nonce);
			expect(toHex(blob.subarray(0, HEADER_SIZE))).toBe(v.preamble);
		});

		it('Seal.decrypt recovers plaintext', () => {
			const blob = hexToBytes(v.blob);
			const out  = Seal.decrypt(cipher, key, blob);
			expect(toHex(out)).toBe(v.plaintext);
		});

		it('OpenStream.finalize recovers plaintext (unified format)', () => {
			const blob     = hexToBytes(v.blob);
			const preamble = blob.subarray(0, HEADER_SIZE);
			const opener   = new OpenStream(cipher, key, preamble);
			const out      = opener.finalize(blob.subarray(HEADER_SIZE));
			expect(toHex(out)).toBe(v.plaintext);
		});
	});
}

runKAT('xc1 (xchacha20, 100B)', xc1);
runKAT('xc_empty (xchacha20, empty)', xc_empty);
runKAT('sc1 (serpent, 100B)', sc1);
runKAT('sc_empty (serpent, empty)', sc_empty);
