name: e2e
on:
  workflow_call:
permissions:
  contents: read
  packages: read
  actions: read
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: ghcr.io/xero/leviathan-crypto/ci:latest
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: install dependencies
        run: bun i
      - name: download build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-${{ github.sha }}
      - name: run e2e browser tests (${{ matrix.browser }})
        env:
          HOME: /root
        run: bunx playwright test --project=${{ matrix.browser }} --reporter=list
