name: lint
on:
  workflow_call:
    inputs:
      bun-version:
        description: 'Bun version to install'
        required: false
        type: string
        default: '1.3.13'
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: ${{ inputs.bun-version }}
      - name: install dependencies
        run: bun i
      - name: full build
        run: bun scripts/build.ts
      - name: lint (ts + asm + tsc x3)
        run: bun scripts/lint.ts
