name: unit-fast
on:
  workflow_call:
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version: 'latest'
      - name: install dependencies
        run: bun i
      - name: build wasm + embedded modules
        run: bun run build:asm && bun run build:embed
      - name: run fast unit tests
        run: >
          bun vitest run --reporter=verbose --no-coverage
          test/unit/init.test.ts
          test/unit/serpent/serpent_kat.test.ts
          test/unit/serpent/serpent_iv.test.ts
          test/unit/serpent/serpent_sbox.test.ts
          test/unit/serpent/serpent_ctr.test.ts
          test/unit/serpent/serpent_cbc.test.ts
          test/unit/serpent/serpent_wipe.test.ts
          test/unit/chacha20/chacha20.test.ts
          test/unit/chacha20/poly1305.test.ts
          test/unit/chacha20/chacha20poly1305.test.ts
          test/unit/chacha20/xchacha20.test.ts
