name: verify-vectors
on:
  workflow_call:
permissions:
  contents: read
jobs:
  hashsums:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: verify test vector checksums
        working-directory: test/vectors
        run: sha256sum --check SHA256SUMS
